PVPArena:
    BlueTeamName: 'Blue'
    RedTeamName: 'Red'
    BlueChannel: 'Transmitt1'
    RedChannel: 'Transmitt2'
    ReverseChannel: 'Reverse1'
    FinishChannel: 'Finish1'
    ResetChannel: 'Reset1'
    GameIsRunningChannel: 'Running1'
    WaitTimeInSeconds: 10
MobArena1:
    ArenaName: 'MobArena1'
    RunningChannel: 'Running2'
    NewWaveChannel: 'NewWave1'
MobArena2:
    ArenaName: 'MobArena2'
    RunningChannel: 'Running3'
    NewWaveChannel: 'NewWave2'